<a href="https://colab.research.google.com/github/mszczepan/data-science-bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np

In [28]:
np.__version__

'1.22.4'

# Norma wektorowa długość wektora R2

In [29]:
v1 = np.array([2, 4])

In [67]:
v1

array([2, 4])

In [30]:
np.linalg.norm(v1)

4.47213595499958

# Norma euklidesowa w Rn

In [31]:
v2 = np.array([-10, 10, 13])

In [32]:
np.linalg.norm(v2)

19.209372712298546

# Odległość dwóch punktów na płaszczyźnie

In [33]:
p = np.array([3, 0])
q = np.array([0, 4])

In [34]:
np.linalg.norm(p - q)

5.0

# Mnożenie macierzy

In [35]:
A = np.array([[5, 3], [3, 9]])

In [36]:
B = np.array([[1], [-1]])

In [37]:
C = np.dot(A, B)
print(A)
print(B)
print(C)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]
[[ 2]
 [-6]]


In [38]:
C.shape

(2, 1)

# Wyznacznik macierzy

In [39]:
A = np.array([[2, 4], [-1, 3]])

In [40]:
np.linalg.det(A)

9.999999999999998

# Ślad macierzy

In [41]:
A = np.array([[2, 4], [-1, 3]])

In [42]:
np.trace(A)

5

# Macierz jednostkowa

In [43]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Macierz odwrotna

In [44]:
A = np.array([[2, 4], [-1, 3]])

In [45]:
B = np.linalg.inv(A)

In [46]:
np.set_printoptions(precision=4,suppress=True)

In [47]:
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [48]:
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

# Macierz Transponowana

In [49]:
A = np.array([[2, 4], [-1, 3]])

In [50]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [51]:
A.T

array([[ 2, -1],
       [ 4,  3]])

# Rozwiązywanie układów równań

Przykład

In [70]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [71]:
B = np.array([10, -1])
print(B)

[10 -1]


In [75]:
A_inv = np.linalg.inv(A)
C = np.dot(A_inv, B)
print(C)

[1. 2.]


In [73]:
C.shape

(2,)