<a href="https://colab.research.google.com/github/mszczepan/data-science-bootcamp/blob/main/01_wprowadzenie/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np


In [8]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],[12.50, 13.00, 11.70, 12.20, 2000], [12.20, 13.40, 12.20, 13.20, 1500]])
price

array([[  12.4,   12.8,   11.9,   12.6, 1000. ],
       [  12.5,   13. ,   11.7,   12.2, 2000. ],
       [  12.2,   13.4,   12.2,   13.2, 1500. ]])

In [9]:
price.sum()

4650.1

In [10]:
#Sumowanie po kolumnach
price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [11]:
#sumowanie po wierszach
price.sum(axis=1)

array([1049.7, 2049.4, 1551. ])

In [12]:
#zwraca minimum
np.min(price)

11.7

In [14]:
#minimum w kolumnach
np.min(price,axis=0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [15]:
#maximum po wierszach
np.max(price,axis=1)

In [16]:
#mediana
np.median(price)

12.6

In [17]:
#średnia
np.mean(price)

310.0066666666667

In [ ]:
#