<a href="https://colab.research.google.com/github/mszczepan/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy

Podstawowa biblioteka do obliczeń numerycznych w języku Python:

strona biblioteki:
https://numpy.org/

# 1.Podstawy


In [2]:
import numpy as np
np.__version__

'1.22.4'

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

1D array

In [5]:
x = np.array([1, 3])

In [6]:
print(x)

[1 3]


In [7]:
type(x)

numpy.ndarray

In [8]:
x.ndim

1

In [9]:
x.shape

(2,)

In [10]:
x.size

2

In [11]:
x.dtype

dtype('int64')

In [12]:
x = np.array([1.1, 1.3, 1.4])

In [13]:
print(x)

[1.1 1.3 1.4]


In [14]:
x.dtype

dtype('float64')

2D Array

In [15]:
x = np.array([[1, 2], [2, 5]])

In [16]:
print(x)

[[1 2]
 [2 5]]


In [17]:
x.ndim

2

In [18]:
x.shape

(2, 2)

In [19]:
x = np.array([[1, 2, 3], [5, 6, 7]])

In [20]:
x

array([[1, 2, 3],
       [5, 6, 7]])

In [21]:
x.shape

(2, 3)

3D array

In [22]:
x = np.array(
    [[[4, 4, 2],
      [5, 9, 8]],
     
     [[6, 7, 9],
      [4, 2, 1]]]
    )

In [23]:
print(x)

[[[4 4 2]
  [5 9 8]]

 [[6 7 9]
  [4 2 1]]]


In [24]:
x.ndim

3

In [25]:
x.shape

(2, 2, 3)

# Typy Danych

In [26]:
A = np.array([1, 2, 3, 4])
A.dtype

dtype('int64')

In [27]:
A = np.array([1.0, 2.0, 3.0])
A.dtype

dtype('float64')

In [28]:
A = np.array([1.0, 'strin', 2.0])
A.dtype

dtype('<U32')

In [29]:
A = np.array([1, 2, 3], dtype = 'float')
A

array([1., 2., 3.])

In [30]:
A = np.array([1.0, 2.0, 3.0], dtype = 'int')
A

array([1, 2, 3])

In [31]:
A = np.array([24, 128, 56], dtype = np.int8)
A.dtype

dtype('int8')

# Tworzenie tablic


In [32]:
np.zeros(shape =(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
np.zeros(shape =(4,10),dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [34]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:

np.full(shape = (5,5), fill_value=5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [36]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(start=5, stop=20, step= 3)

array([ 5,  8, 11, 14, 17])

In [38]:
np.linspace(start=4, stop=10, num =4, dtype='int')

array([ 4,  6,  8, 10])

In [39]:
A = np.arange(15)

In [40]:
A.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
A.reshape(3,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# Podstawowe operacje na tablicach

In [44]:
A = np.array([1, 3, 5, 6])
B = np.array([-2, -5, 4, 1])

In [45]:
A + B

array([-1, -2,  9,  7])

In [46]:
A - B

array([3, 8, 1, 5])

In [47]:
A * B

array([ -2, -15,  20,   6])

In [48]:
A/B

array([-0.5 , -0.6 ,  1.25,  6.  ])

In [49]:
A + 3

array([4, 6, 8, 9])

In [50]:
A - 3

array([-2,  0,  2,  3])

In [51]:
A * 2

array([ 2,  6, 10, 12])

In [52]:
np.add(A, B)

array([-1, -2,  9,  7])

In [53]:
np.subtract(A, B)

array([3, 8, 1, 5])

In [54]:
np.divide(A, B)

array([-0.5 , -0.6 ,  1.25,  6.  ])

In [55]:
np.multiply(A, B)

array([ -2, -15,  20,   6])

In [61]:
X = np.array([[1, 2], [3, -2]])
Y = np.array([[5, 7], [-2, -5]])
print(X)

[[ 1  2]
 [ 3 -2]]


In [63]:
print(Y)

[[ 5  7]
 [-2 -5]]


In [59]:
X * Y

array([[ 5, 14],
       [-6, 10]])

In [60]:
np.dot(X, Y)

array([[ 1, -3],
       [19, 31]])

In [64]:
X.dot(Y)

array([[ 1, -3],
       [19, 31]])

In [65]:
X @ Y

array([[ 1, -3],
       [19, 31]])

# Generowanie liczb pseudolosowych

In [66]:
np.random.seed(0)

In [67]:
np.random.randn()

1.764052345967664

In [68]:
np.random.randn(5)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788])