<a href="https://colab.research.google.com/github/mszczepan/data-science-bootcamp/blob/main/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.__version__

'1.22.4'

# Norma wektorowa długość wektora R2

In [3]:
v1 = np.array([2, 4])

In [4]:
np.linalg.norm(v1)

4.47213595499958

# Norma euklidesowa w Rn

In [5]:
v2 = np.array([-10, 10, 13])

In [6]:
np.linalg.norm(v2)

19.209372712298546

# Odległość dwóch punktów na płaszczyźnie

In [7]:
p = np.array([3, 0])
q = np.array([0, 4])

In [8]:
np.linalg.norm(p - q)

5.0

# Mnożenie macierzy

In [10]:
A = np.array([[5, 3], [3, 9]])

In [11]:
B = np.array([[1], [-1]])

In [15]:
C = np.dot(A, B)
print(A)
print(B)
print(C)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]
[[ 2]
 [-6]]


In [18]:
C.shape

(2, 1)

# Wyznacznik macierzy 

In [20]:
A = np.array([[2, 4], [-1, 3]])

In [21]:
np.linalg.det(A)

9.999999999999998

# Ślad macierzy

In [22]:
A = np.array([[2, 4], [-1, 3]])

In [23]:
np.trace(A)

5

# Macierz jednostkowa

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Macierz odwrotna

In [25]:
A = np.array([[2, 4], [-1, 3]])

In [28]:
B = np.linalg.inv(A)

In [31]:
np.set_printoptions(precision=4,suppress=True)

In [30]:
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [32]:
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

# Macierz Transponowana

In [33]:
A = np.array([[2, 4], [-1, 3]])

In [34]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [35]:
A.T

array([[ 2, -1],
       [ 4,  3]])